name: publish-pypi
run-name: "Publish to PyPI"
on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - run: python3 -m pip install poetry
      - run: poetry build
      - uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/
      - uses: pypa/gh-action-pypi-publish@release/v1

  release:
    runs-on: ubuntu-latest
    needs:
      - publish
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/
      - shell: "bash"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" ./dist/*.whl \
          --repo "${GITHUB_REPOSITORY}" \
          --title "${GITHUB_REPOSITORY#*/} ${tag}" \
          --generate-notes
